// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKI191Af805JYym_vbEA6g7eJqlhj2quM',
    appId: '1:282805273447:web:6e2bf5c4de98957b15e5c2',
    messagingSenderId: '282805273447',
    projectId: 'mypiety-9a56c',
    authDomain: 'mypiety-9a56c.firebaseapp.com',
    databaseURL: 'https://mypiety-9a56c.firebaseio.com',
    storageBucket: 'mypiety-9a56c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgcoyaaHRePItHBPkMkDi15P8-qLdki8k',
    appId: '1:282805273447:android:aa26b419c63628fb15e5c2',
    messagingSenderId: '282805273447',
    projectId: 'mypiety-9a56c',
    databaseURL: 'https://mypiety-9a56c.firebaseio.com',
    storageBucket: 'mypiety-9a56c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOlA1JtZgLI4hm7-KL27SdofmL6fLEm5Y',
    appId: '1:282805273447:ios:c3235b69ccef6e4515e5c2',
    messagingSenderId: '282805273447',
    projectId: 'mypiety-9a56c',
    databaseURL: 'https://mypiety-9a56c.firebaseio.com',
    storageBucket: 'mypiety-9a56c.appspot.com',
    androidClientId: '282805273447-03ijur9nirat8ikmchcqfsjqkrv6inkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pietyservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOlA1JtZgLI4hm7-KL27SdofmL6fLEm5Y',
    appId: '1:282805273447:ios:c3235b69ccef6e4515e5c2',
    messagingSenderId: '282805273447',
    projectId: 'mypiety-9a56c',
    databaseURL: 'https://mypiety-9a56c.firebaseio.com',
    storageBucket: 'mypiety-9a56c.appspot.com',
    androidClientId: '282805273447-03ijur9nirat8ikmchcqfsjqkrv6inkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pietyservices',
  );
}
